# Generated by Django 2.1.dev20171223092632 on 2018-01-03 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='house_title',
            new_name='house_name',
        ),
    ]
