# Generated by Django 2.1.dev20171223092632 on 2018-01-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_auto_20180103_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='houses',
            name='thumb',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
