# Generated by Django 2.1.dev20171223092632 on 2018-01-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_houses_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='houses',
            name='body',
            field=models.TextField(default=None),
        ),
    ]
