# Generated by Django 2.1.dev20171223092632 on 2018-01-06 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0014_auto_20180106_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
