# Generated by Django 2.1.dev20171223092632 on 2018-01-06 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0015_auto_20180106_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
