# Generated by Django 2.1.dev20171223092632 on 2018-01-06 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0016_auto_20180106_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houses',
            name='author',
        ),
    ]
