# Generated by Django 2.1.dev20171223092632 on 2018-01-06 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0019_auto_20180106_0157'),
    ]

    operations = [
        migrations.CreateModel(
            name='house',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=10)),
                ('house_name', models.CharField(max_length=250)),
                ('houses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.Houses')),
            ],
        ),
    ]
