# Generated by Django 2.1.dev20171223092632 on 2018-01-06 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0020_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houses',
            name='author',
        ),
    ]
