# Generated by Django 2.1.dev20171223092632 on 2018-01-06 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0021_remove_houses_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=100)),
                ('your_email', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(default=None)),
            ],
        ),
    ]
